# Whenever this file is updated, you need to regenerate *.lock files. Run
#
#   conda-lock -p osx-64 -p linux-64 -f environment.yml --filename-template "environment.{platform}.lock"
#
# conda-lock is avialable from pip
#
#   pip install conda-lock
#
# or conda/mamba
#
#   conda install conda-lock
#
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::cutadapt>=3.4
  - bioconda::dnaio
  - bioconda::fastqc
  - conda-forge::ipython>=7
  - conda-forge::jupyter
  - bioconda::multiqc>=1.11
  - conda-forge::numpy
  - conda-forge::pandas>=2
  - conda-forge::pigz
  - conda-forge::pip
  - bioconda::pysam>=0.16
  - conda-forge::python=3.9.*
  - conda-forge::ruamel.yaml
  - conda-forge::seaborn>=0.11.1
  - bioconda::seqtk>=1.3
  - bioconda::snakemake-minimal>=6.1.2
  - bioconda::starcode=1.4
  - conda-forge::tqdm
  - bioconda::umi_tools>=1.1.1
