$schema: "http://json-schema.org/draft-06/schema#"
description: Configuration parameters for running BLR pipeline
properties:
  dbs:
    type: string
    description: IUPAC string for DBS sequence
  dbs_len_span:
    type: number
    description: Span (+/-) relative DBS_len for accepted DBS i.e for 1 the span is DBS_len-1 to DBS_len+1 bp.
  umi_len:
    type: number
    description: Length in basepairs of UMI sequence
  abc_umi_len_span:
    type: number
    description: Span (+/-) relative the sum of the ABC and UMI lengths
  trim_err_rate:
    type: number
    description: Error-rate for handle trimming
    default: 0.2
  demultiplex_err_rate:
    type: number
    description: Error rate for demultiplexing ABC sequences..
    default: 0.2
  abc_file:
    type: string
    default: "ABC-sequences.fasta"
    description: Fasta file containing target information.
  h1:
    type: ["string", "null"]
    description: h1 adaptor sequence, appears before droplet barcode
  h2:
    type: string
    description: h2 adaptor sequence, appears after droplet barcode
  h3:
    type: string
    description: h3 adaptor sequence, appears after Ab-barcode and UMI
  dbs_cluster_dist:
    type: number
    description: Maximum edit distance to cluster DBS sequences in Starcode.
    default: 2
  abc_cluster_dist:
    type: number
    description: Maximum edit distance to cluster ABC sequences in Starcode.
    default: 1
  filter_reads:
    typw: number
    description: Minimum reads required for an ABC to be included in analysis output.
    default: 1
