top_modules:
  - cutadapt:
      name: "Cutadapt (Extract ABC-UMI)"
      path_filters:
        - "*cutadapt-extract-abc-umi.log"
  - cutadapt:
      name: "Cutadapt (Extract DBS)"
      path_filters:
        - "*cutadapt-extract-dbs.log"
  - fastqc:
      name: "FastQC (Extract ABC-UMI)"
      path_filters:
        - "*trimmed-abc_fastqc.zip"
  - fastqc:
      name: "FastQC (Extract DBS)"
      path_filters:
        - "*dbs-raw_fastqc.zip"

run_modules:
  - fastqc
  - cutadapt

extra_fn_clean_trim:
  - ".subsampled"
  - ".dbs-raw"
