top_modules:
  - fastqc:
      name: "FastQC (Raw)"
      path_filters:
        - "*_fastqc.zip"
  - fastqc:
      name: "FastQC (Trimmed)"
      path_filters:
        - "*trimmed_fastqc.zip"

run_modules:
  - fastqc
  - cutadapt
  - preseq

extra_fn_clean_trim:
  - ".subsampled"
  - ".preseq"
