name: CI Linux

on: 
  push:
    branch:
      - master
      - dev
  pull_request:
    branch:
      - master
      - dev
  schedule:
    - cron: 0 7 * * 5

jobs:
  run:
    name: Run pipeline
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          auto-update-conda: false
          environment-file: environment.linux-64.lock
      - name: Install and check env
        run: |
          conda activate testenv
          pip install .[dev]
          conda info
          conda list
          dbspro --version
      - name: Run flake8
        run: |
          conda activate testenv
          flake8 src/ tests/
          flake8 --select=W292 --filename '*.yaml,*.yml'
      - name: Clone test data
        uses: actions/checkout@v2
        with:
          repository: AfshinLab/DBS-Pro_testdata
          path: testdata
      - name: Run tests
        run: |
          conda activate testenv
          # Required to make umi-tools output consistent. 
          export PYTHONHASHSEED=1 
          pytest -v tests/
